# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bafc7e17df1d914ba5a3f8935bd25ed0d01df86f96c76c236aaa68769d5b197773c0025dbc693074f1a1efaef1a7c969814822927b4d24f4275bd41125315980

test:
  secret_key_base: 6269b79d75d4adc0be0a6b2b041669e5faa67bce1a4072c6ebaa0a8f3be041381e2eede50a2ca2f0fdc8f2c165b59d58a3f150ed6e0335df81faae12fab6e941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
